# Generated by Django 3.2.4 on 2021-07-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variaton_category',
            new_name='variation_category',
        ),
    ]
