# Generated by Django 3.2.4 on 2021-07-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
